routes/web.php
<?php

use App\Http\Controllers\Admin\AuctionController;
use App\Http\Controllers\Admin\CreditProductsController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Customer\BidAuctionController;
use App\Http\Controllers\BuyCreditController;
use App\Http\Controllers\BuyoutAuctionController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Public
Route::get('/', [HomeController::class, 'index'])->name('home');

// Customer
Route::middleware('auth')->group(function () {
    Route::post('bid', [BidAuctionController::class, 'bid'])->name('bid');
    Route::post('buyout', [BuyoutAuctionController::class, 'buyout'])->name('buyout');
    Route::post('buy-credit', [BuyCreditController::class, 'buy'])->name('buy_credit');
});

// Admin
Route::name('admin.')->prefix('admin')->middleware('auth')->group(function () {
    Route::get('/dashboard', function () {
        return view('admin.dashboard');
    })->name('dashboard');

    Route::resource('products', ProductController::class);
    Route::resource('auctions', AuctionController::class);
    Route::resource('credit-products', CreditProductsController::class);
});

// Temporary helpers
Route::get('/token', function () {
    return csrf_token();
});


require __DIR__.'/auth.php';

app/Models/Auction.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Auction extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'name',
        'status',
        'product_price',
        'buyout_price',
        'bid_value',
        'minimum_quota',
        'quota_value',
        'bid_interval_in_seconds',
        'start_at',
        'end_at',
    ];

    protected $casts = [
        'bid_interval_in_seconds' => 'integer',
        'start_at' => 'datetime',
        'end_at' => 'datetime',
    ];

    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class);
    }

    public function bids(): HasMany
    {
        return $this->hasMany(Bid::class);
    }

    public function canBid(): bool {
        if (AuctionStatus::FINISHED == $this->status) {
            return false;
        }
        if ($this->latestBid() == null) {
            return true;
        }

        $time_limit = $this->latestBid()->created_at->addSeconds($this->bid_interval_in_seconds);
        $now = new Carbon();

        if ($now->lessThan($time_limit)) {
            return true;
        }
        return false;
    }

    public function latestBid() {
        return $this->bids()->orderBy('created_at', 'desc')->limit(1)->first();
    }

    public function setStatusAttribute($value) {
        if (AuctionStatus::isValid($value)) {
            $this->attributes['status'] = $value;
            return;
        }
        throw new \Exception('Invalid auction status');
    }

    public function scopeOpen($query)
    {
        return $query->where('status', '=', AuctionStatus::OPEN);
    }
}

app/Http/Controllers/Admin/AuctionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Events\AuctionCreated;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Auction\CreateAuctionRequest;
use App\Http\Requests\Admin\Auction\UpdateAuctionRequest;
use App\Models\Auction;
use App\Models\AuctionStatus;
use App\Models\Product;
use Illuminate\Auth\Events\Registered;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class AuctionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index()
    {
        $auctions = Auction::paginate(5);

        return view('admin.auctions.index', compact('auctions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create()
    {
        $products = Product::all();

        return view('admin.auctions.create', compact('products'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  CreateAuctionRequest  $request
     * @return RedirectResponse
     */
    public function store(CreateAuctionRequest $request)
    {
        $product = Product::findOrFail($request->product_id);

        $auction = new Auction();
        $auction->product()->associate($product);
        $auction->status = AuctionStatus::OPEN;
        $auction->name = $request->name;
        $auction->product_price = $request->product_price;
        $auction->buyout_price = $request->buyout_price;
        $auction->bid_value = $request->bid_value;
        $auction->minimum_quota = $request->minimum_quota;
        $auction->quota_value = $request->quota_value;
        $auction->bid_interval_in_seconds = $request->bid_interval_in_seconds;
        $auction->start_at = $request->start_at;
        $auction->end_at = $request->end_at;
        $auction->save();

        event(new AuctionCreated($auction));

        return redirect()->route('admin.auctions.show', ['auction' => $auction->id ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return View
     */
    public function show($id)
    {
        $products = Product::all();
        $auction = Auction::findOrFail($id);
        return view('admin.auctions.show', compact('auction', 'products'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return View
     */
    public function edit($id)
    {
        $products = Product::all();
        $auction = Auction::find($id);
        return view('admin.auctions.edit', compact('auction', 'products'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateAuctionRequest  $request
     * @param  int  $id
     * @return RedirectResponse
     */
    public function update(UpdateAuctionRequest $request, $id)
    {
        $product = Product::findOrFail($request->product_id);

        $auction = Auction::find($id);
        $auction->product()->associate($product);
        $auction->name = $request->name;
        $auction->product_price = $request->product_price;
        $auction->buyout_price = $request->buyout_price;
        $auction->bid_value = $request->bid_value;
        $auction->minimum_quota = $request->minimum_quota;
        $auction->quota_value = $request->quota_value;
        $auction->bid_interval_in_seconds = $request->bid_interval_in_seconds;
        $auction->start_at = $request->start_at;
        $auction->end_at = $request->end_at;
        $auction->save();

        return redirect()->route('admin.auctions.show', ['auction' => $auction->id ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return RedirectResponse
     */
    public function destroy($id)
    {
        Auction::destroy($id);

        return redirect()->route('admin.auctions.index');
    }
}

resources/views/admin/auctions/create.blade.php
<x-admin::admin-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Auctions') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <x-admin::subtitle :subtitle="'Create Auction'"></x-admin::subtitle>
                    <!-- Validation Errors -->
                    <x-admin::form-validation-errors class="mb-4" :errors="$errors" />
                    <form action="{{ route('admin.auctions.store') }}" method="post">
                        @method('POST')
                        @csrf
                        <div class="mt-8 max-w-md">
                            <div class="grid grid-cols-1 gap-6">
                                <label class="block">
                                    <span class="text-gray-700">Name</span>
                                    <input type="text" name="name" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="">
                                </label>
                                <label class="block">
                                    <span class="text-gray-700">Product</span>
                                    <select name="product_id" class="block w-full mt-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">\
                                        @foreach($products as $product)
                                            <option value="{{ $product->id }}">{{ $product->name }}</option>
                                        @endforeach
                                    </select>
                                </label>
                                <label class="block">
                                    <span class="text-gray-700">Price</span>
                                    <input type="number" name="product_price"  min="1" step="any" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="">
                                </label>
                                <label class="block">
                                    <span class="text-gray-700">Buyout Price</span>
                                    <input type="number" name="buyout_price"  min="1" step="any" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="">
                                </label>
                                <label class="block">
                                    <span class="text-gray-700">Bid Value</span>
                                    <input type="number" name="bid_value"  min="1" step="any" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="">
                                </label>
                                <label class="block">
                                    <span class="text-gray-700">Minimum Quota</span>
                                    <input type="number" name="minimum_quota"  min="0" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="">
                                </label>
                                <label class="block">
                                    <span class="text-gray-700">Quota Value</span>
                                    <input type="number" name="quota_value"  min="1" step="any" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="">
                                </label>
                                <label class="block">
                                    <span class="text-gray-700">Bid interval in seconds</span>
                                    <input type="number" name="bid_interval_in_seconds"  min="0" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="">
                                </label>
                                <label class="block">
                                    <span class="text-gray-700">Start At</span>
                                    <input type="text" name="start_at"  min="0" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="">
                                </label>
                                <label class="block">
                                    <span class="text-gray-700">End At</span>
                                    <input type="text" name="end_at"  min="0" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="">
                                </label>
                                <div class="md:flex">
                                    <div class="md:w-2/3">
                                        <input type="submit" class="shadow bg-purple-500 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" value="Create">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-admin::admin-layout>

resources/views/admin/auctions/edit.blade.php
<x-admin::admin-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Auctions') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <x-admin::subtitle :subtitle="'Edit Auction'"></x-admin::subtitle>
                    <!-- Validation Errors -->
                    <x-admin::form-validation-errors class="mb-4" :errors="$errors" />
                    <form action="{{ route('admin.auctions.update', ['auction' => $auction->id ]) }}" method="post">
                        @method('PUT')
                        @csrf
                        <div class="grid grid-cols-1 gap-6">
                            <label class="block">
                                <span class="text-gray-700">Name</span>
                                <input type="text" name="name" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $auction->name }}">
                            </label>
                            <label class="block">
                                <span class="text-gray-700">Product</span>
                                <select name="product_id" class="block w-full mt-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">\
                                    @foreach($products as $product)
                                        <option value="{{ $product->id }}" @if($auction->id == $product->id) selected @endif>{{ $product->name }}</option>
                                    @endforeach
                                </select>
                            </label>
                            <label class="block">
                                <span class="text-gray-700">Price</span>
                                <input type="number" name="product_price"  min="1" step="any" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $auction->product_price }}">
                            </label>
                            <label class="block">
                                <span class="text-gray-700">Buyout Price</span>
                                <input type="number" name="buyout_price"  min="1" step="any" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $auction->buyout_price }}">
                            </label>
                            <label class="block">
                                <span class="text-gray-700">Bid Value</span>
                                <input type="number" name="bid_value"  min="1" step="any" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $auction->bid_value }}">
                            </label>
                            <label class="block">
                                <span class="text-gray-700">Minimum Quota</span>
                                <input type="number" name="minimum_quota"  min="0" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $auction->minimum_quota }}">
                            </label>
                            <label class="block">
                                <span class="text-gray-700">Quota Value</span>
                                <input type="number" name="quota_value"  min="1" step="any" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $auction->quota_value }}">
                            </label>
                            <label class="block">
                                <span class="text-gray-700">Bid interval in seconds</span>
                                <input type="number" name="bid_interval_in_seconds"  min="0" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $auction->bid_interval_in_seconds }}">
                            </label>
                            <label class="block">
                                <span class="text-gray-700">Start At</span>
                                <input type="text" name="start_at"  min="0" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $auction->start_at }}">
                            </label>
                            <label class="block">
                                <span class="text-gray-700">End At</span>
                                <input type="text" name="end_at"  min="0" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $auction->end_at }}">
                            </label>
                            <div class="md:flex">
                                <div class="md:w-2/3">
                                    <input type="submit" class="shadow bg-purple-500 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" value="Create">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-admin::admin-layout>

resources/views/admin/auctions/index.blade.php
<x-admin::admin-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Auctions') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <a href="{{ route('admin.auctions.create') }}" class="float-right shadow bg-purple-500 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded">
                        Create
                    </a>
                    <x-admin::subtitle :subtitle="'Auction List'"></x-admin::subtitle>


                    <x-admin::table :entity="'auction'" :data="$auctions" :headers="array('Name' => 'name', 'Product' => ['product', 'name'])">
                    </x-admin::table>
                </div>
            </div>
        </div>
    </div>
</x-admin::admin-layout>

resources/views/admin/auctions/show.blade.php
<x-admin::admin-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Auctions') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <x-admin::subtitle :subtitle="'Show Auction'"></x-admin::subtitle>
                    @method('PUT')
                    @csrf
                    <div class="mt-8 max-w-md">
                        <div class="grid grid-cols-1 gap-6">
                            <label class="block">
                                <span class="text-gray-700">Name</span>
                                <input disabled type="text" name="name" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $auction->name }}">
                            </label>
                            <label class="block">
                                <span class="text-gray-700">Product</span>
                                <select disabled name="product_id" class="block w-full mt-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">\
                                    @foreach($products as $product)
                                        <option value="{{ $product->id }}" @if($auction->id == $product->id) selected @endif>{{ $product->name }}</option>
                                    @endforeach
                                </select>
                            </label>
                            <label class="block">
                                <span class="text-gray-700">Price</span>
                                <input disabled type="number" name="product_price"  min="1" step="any" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $auction->product_price }}">
                            </label>
                            <label class="block">
                                <span class="text-gray-700">Buyout Price</span>
                                <input disabled type="number" name="buyout_price"  min="1" step="any" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $auction->buyout_price }}">
                            </label>
                            <label class="block">
                                <span class="text-gray-700">Bid Value</span>
                                <input disabled type="number" name="bid_value"  min="1" step="any" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $auction->bid_value }}">
                            </label>
                            <label class="block">
                                <span class="text-gray-700">Minimum Quota</span>
                                <input disabled type="number" name="minimum_quota"  min="0" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $auction->minimum_quota }}">
                            </label>
                            <label class="block">
                                <span class="text-gray-700">Quota Value</span>
                                <input disabled type="number" name="quota_value"  min="1" step="any" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $auction->quota_value }}">
                            </label>
                            <label class="block">
                                <span class="text-gray-700">Bid interval in seconds</span>
                                <input disabled type="number" name="bid_interval_in_seconds"  min="0" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $auction->bid_interval_in_seconds }}">
                            </label>
                            <label class="block">
                                <span class="text-gray-700">Start At</span>
                                <input disabled type="text" name="start_at"  min="0" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $auction->start_at }}">
                            </label>
                            <label class="block">
                                <span class="text-gray-700">End At</span>
                                <input disabled type="text" name="end_at"  min="0" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $auction->end_at }}">
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-admin::admin-layout>