routes/web.php
<?php

use App\Http\Controllers\Admin\AuctionController;
use App\Http\Controllers\Admin\CreditProductsController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Customer\BidAuctionController;
use App\Http\Controllers\BuyCreditController;
use App\Http\Controllers\BuyoutAuctionController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Public
Route::get('/', [HomeController::class, 'index'])->name('home');

// Customer
Route::middleware('auth')->group(function () {
    Route::post('bid', [BidAuctionController::class, 'bid'])->name('bid');
    Route::post('buyout', [BuyoutAuctionController::class, 'buyout'])->name('buyout');
    Route::post('buy-credit', [BuyCreditController::class, 'buy'])->name('buy_credit');
});

// Admin
Route::name('admin.')->prefix('admin')->middleware('auth')->group(function () {
    Route::get('/dashboard', function () {
        return view('admin.dashboard');
    })->name('dashboard');

    Route::resource('products', ProductController::class);
    Route::resource('auctions', AuctionController::class);
    Route::resource('credit-products', CreditProductsController::class);
});

// Temporary helpers
Route::get('/token', function () {
    return csrf_token();
});


require __DIR__.'/auth.php';

app/Http/Controllers/Admin/CreditProductsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\CreditProduct\CreateCreditProduct;
use App\Http\Requests\Admin\CreditProduct\UpdateCreditProduct;
use App\Models\Product;
use App\Models\ProductType;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class CreditProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index()
    {
        $creditProducts = Product::creditType()->paginate(5);

        return view('admin.credit-products.index', compact('creditProducts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create()
    {
        return view('admin.credit-products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  CreateCreditProduct  $request
     * @return RedirectResponse
     */
    public function store(CreateCreditProduct $request)
    {
        $creditProduct = new Product();
        $creditProduct->type = ProductType::CREDIT;
        $creditProduct->name = $request->name;
        $creditProduct->quantity = $request->quantity;
        $creditProduct->price = $request->price;
        $creditProduct->save();

        return redirect()->route('admin.credit-products.show', ['credit_product' => $creditProduct->id ]);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return View
     */
    public function show($id)
    {
        $creditProduct = Product::find($id);
        return view('admin.credit-products.show', compact('creditProduct'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return View
     */
    public function edit($id)
    {
        $creditProduct = Product::find($id);
        return view('admin.credit-products.edit', compact('creditProduct'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateCreditProduct  $request
     * @param  int  $id
     * @return RedirectResponse
     */
    public function update(UpdateCreditProduct $request, $id)
    {
        $creditProduct = Product::find($id);
        $creditProduct->name = $request->name;
        $creditProduct->quantity = $request->quantity;
        $creditProduct->price = $request->price;
        $creditProduct->save();

        return redirect()->route('admin.credit-products.show', ['credit_product' => $creditProduct->id ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return RedirectResponse
     */
    public function destroy($id)
    {
        Product::destroy($id);

        return redirect()->route('admin.credit-products.index');

    }
}

resources/views/admin/credit-products/create.blade.php
<x-admin::admin-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Credit-products') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <x-admin::subtitle :subtitle="'Create Credit Product'"></x-admin::subtitle>
                    <!-- Validation Errors -->
                    <x-admin::form-validation-errors class="mb-4" :errors="$errors" />
                    <form action="{{ route('admin.credit-products.store') }}" method="post">
                        @method('POST')
                        @csrf
                        <div class="mt-8 max-w-md">
                            <div class="grid grid-cols-1 gap-6">
                                <label class="block">
                                    <span class="text-gray-700">Name</span>
                                    <input type="text" name="name" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="">
                                </label>
                                <label class="block">
                                    <span class="text-gray-700">Price</span>
                                    <input type="number" name="price"  min="1" step="any" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="">
                                </label>
                                <label class="block">
                                    <span class="text-gray-700">Quantity</span>
                                    <input type="number" name="quantity"  min="1" step="any" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="">
                                </label>
                                <div class="md:flex">
                                    <div class="md:w-2/3">
                                        <input type="submit" class="shadow bg-purple-500 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" value="Create">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-admin::admin-layout>

resources/views/admin/credit-products/edit.blade.php
<x-admin::admin-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Credit-products') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <x-admin::subtitle :subtitle="'Edit Credit Product'"></x-admin::subtitle>
                    <!-- Validation Errors -->
                    <x-admin::form-validation-errors class="mb-4" :errors="$errors" />
                    <form action="{{ route('admin.credit-products.update', ['credit_product' => $creditProduct->id ]) }}" method="post">
                        @method('PUT')
                        @csrf
                        <div class="mt-8 max-w-md">
                            <div class="grid grid-cols-1 gap-6">
                                <label class="block">
                                    <span class="text-gray-700">Name</span>
                                    <input type="text" name="name" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $creditProduct->name }}">
                                </label>
                                <label class="block">
                                    <span class="text-gray-700">Price</span>
                                    <input type="number" name="price"  min="1" step="any" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $creditProduct->price }}">
                                </label>
                                <label class="block">
                                    <span class="text-gray-700">Quantity</span>
                                    <input type="number" name="quantity"  min="1" step="any" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $creditProduct->quantity }}">
                                </label>
                                <div class="md:flex">
                                    <div class="md:w-2/3">
                                        <input type="submit" class="shadow bg-purple-500 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" value="Edit">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-admin::admin-layout>

resources/views/admin/credit-products/index.blade.php
<x-admin::admin-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Credit-products') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <a href="{{ route('admin.credit-products.create') }}" class="float-right shadow bg-purple-500 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded">
                        Create
                    </a>
                    <x-admin::subtitle :subtitle="'Credit Product List'"></x-admin::subtitle>

                    <x-admin::table :entity="'credit-product'" :data="$creditProducts" :headers="array('Name' => 'name', 'Price' => 'price', 'Quantity' => 'quantity')">
                    </x-admin::table>
                </div>
            </div>
        </div>
    </div>
</x-admin::admin-layout>

resources/views/admin/credit-products/show.blade.php
<x-admin::admin-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Credit-products') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <x-admin::subtitle :subtitle="'Show Credit Product'"></x-admin::subtitle>
                    @method('PUT')
                    @csrf
                    <div class="mt-8 max-w-md">
                        <div class="grid grid-cols-1 gap-6">
                            <label class="block">
                                <span class="text-gray-700">Name</span>
                                <input type="text" name="name" disabled class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $creditProduct->name }}">
                            </label>
                            <label class="block">
                                <span class="text-gray-700">Price</span>
                                <input type="number" name="price" disabled min="1" step="any" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $creditProduct->price }}">
                            </label>
                            <label class="block">
                                <span class="text-gray-700">Quantity</span>
                                <input type="number" name="quantity" disabled min="1" step="any" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $creditProduct->quantity }}">
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-admin::admin-layout>