routes/web.php
<?php

use App\Http\Controllers\Admin\AuctionController;
use App\Http\Controllers\Admin\CreditProductsController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Customer\BidAuctionController;
use App\Http\Controllers\BuyCreditController;
use App\Http\Controllers\BuyoutAuctionController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Public
Route::get('/', [HomeController::class, 'index'])->name('home');

// Customer
Route::middleware('auth')->group(function () {
    Route::post('bid', [BidAuctionController::class, 'bid'])->name('bid');
    Route::post('buyout', [BuyoutAuctionController::class, 'buyout'])->name('buyout');
    Route::post('buy-credit', [BuyCreditController::class, 'buy'])->name('buy_credit');
});

// Admin
Route::name('admin.')->prefix('admin')->middleware('auth')->group(function () {
    Route::get('/dashboard', function () {
        return view('admin.dashboard');
    })->name('dashboard');

    Route::resource('products', ProductController::class);
    Route::resource('auctions', AuctionController::class);
    Route::resource('credit-products', CreditProductsController::class);
});

// Temporary helpers
Route::get('/token', function () {
    return csrf_token();
});


require __DIR__.'/auth.php';

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'name',
        'type',
        'price',
        'quantity',
    ];

    public function auctions(): HasMany
    {
        return $this->hasMany(Auction::class);
    }

    public function scopeProductType($query)
    {
        return $query->where('type', '=', ProductType::PRODUCT);
    }

    public function scopeCreditType($query)
    {
        return $query->where('type', '=', ProductType::CREDIT);
    }

    public function setTypeAttribute($value) {
        if (ProductType::isValid($value)) {
            $this->attributes['type'] = $value;
            return;
        }
        throw new \Exception('Invalid bid type');
    }
}

app/Models/ProductType.php
<?php

namespace App\Models;

class ProductType
{
    const PRODUCT = 'PRODUCT';
    const CREDIT = 'CREDIT';

    public static function isValid($value): bool
    {
        $validValues = [ProductType::PRODUCT, ProductType::CREDIT];

        if (in_array($value, $validValues)) {
            return true;
        }
        return false;
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Product\CreateProductRequest;
use App\Http\Requests\Admin\Product\UpdateProductRequest;
use App\Models\Product;
use App\Models\ProductType;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index()
    {
        $products = Product::productType()->paginate(5);

        return view('admin.products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create()
    {
        return view('admin.products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  CreateProductRequest  $request
     * @return RedirectResponse
     */
    public function store(CreateProductRequest $request)
    {
        $product = new Product();
        $product->name = $request->name;
        $product->type = ProductType::PRODUCT;
        $product->price = $request->price;
        $product->quantity = 1;
        $product->save();

        return redirect()->route('admin.products.show', ['product' => $product->id ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return View
     */
    public function show($id)
    {
        $product = Product::find($id);
        return view('admin.products.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return View
     */
    public function edit($id)
    {
        $product = Product::find($id);
        return view('admin.products.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateProductRequest  $request
     * @param  int  $id
     * @return RedirectResponse
     */
    public function update(UpdateProductRequest $request, $id)
    {
        $product = Product::find($id);
        $product->name = $request->name;
        $product->price = $request->price;
        $product->save();

        return redirect()->route('admin.products.show', ['product' => $product->id ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return RedirectResponse
     */
    public function destroy($id)
    {
        Product::destroy($id);

        return redirect()->route('admin.products.index');
    }
}

resources/views/admin/products/create.blade.php
<x-admin::admin-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Products') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <x-admin::subtitle :subtitle="'Create Product'"></x-admin::subtitle>
                    <!-- Validation Errors -->
                    <x-admin::form-validation-errors class="mb-4" :errors="$errors" />
                    <form action="{{ route('admin.products.store') }}" method="post">
                        @method('POST')
                        @csrf
                        <div class="mt-8 max-w-md">
                            <div class="grid grid-cols-1 gap-6">
                                <label class="block">
                                    <span class="text-gray-700">Name</span>
                                    <input type="text" name="name" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="">
                                </label>
                                <label class="block">
                                    <span class="text-gray-700">Price</span>
                                    <input type="number" name="price"  min="1" step="any" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="">
                                </label>
                                <div class="md:flex">
                                    <div class="md:w-2/3">
                                        <input type="submit" class="shadow bg-purple-500 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" value="Create">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-admin::admin-layout>

resources/views/admin/products/edit.blade.php
<x-admin::admin-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Products') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <x-admin::subtitle :subtitle="'Edit Product'"></x-admin::subtitle>
                    <!-- Validation Errors -->
                    <x-admin::form-validation-errors class="mb-4" :errors="$errors" />
                    <form action="{{ route('admin.products.update', ['product' => $product->id ]) }}" method="post">
                        @method('PUT')
                        @csrf
                        <div class="mt-8 max-w-md">
                            <div class="grid grid-cols-1 gap-6">
                                <label class="block">
                                    <span class="text-gray-700">Name</span>
                                    <input type="text" name="name" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $product->name }}">
                                </label>
                                <label class="block">
                                    <span class="text-gray-700">Price</span>
                                    <input type="number" name="price"  min="1" step="any" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $product->price }}">
                                </label>
                                <div class="md:flex">
                                    <div class="md:w-2/3">
                                        <input type="submit" class="shadow bg-purple-500 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" value="Edit">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-admin::admin-layout>

resources/views/admin/products/index.blade.php
<x-admin::admin-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Products') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <a href="{{ route('admin.products.create') }}" class="float-right shadow bg-purple-500 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded">
                        Create
                    </a>
                    <x-admin::subtitle :subtitle="'Product List'"></x-admin::subtitle>

                    <x-admin::table :entity="'product'" :data="$products" :headers="array('Name' => 'name', 'Price' => 'price')">
                    </x-admin::table>
                </div>
            </div>
        </div>
    </div>
</x-admin::admin-layout>

resources/views/admin/products/show.blade.php
<x-admin::admin-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Products') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <x-admin::subtitle :subtitle="'Show Product'"></x-admin::subtitle>
                    @method('PUT')
                    @csrf
                    <div class="mt-8 max-w-md">
                        <div class="grid grid-cols-1 gap-6">
                            <label class="block">
                                <span class="text-gray-700">Name</span>
                                <input type="text" name="name" disabled class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $product->name }}">
                            </label>
                            <label class="block">
                                <span class="text-gray-700">Price</span>
                                <input type="number" name="price" disabled min="1" step="any" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" placeholder="" value="{{ $product->price }}">
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-admin::admin-layout>